name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout (V3)
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      # run: npm run test:headless

      - name: Build
        run: npm run build:prod

      - name: Upload artifact(Action to Update artifact)
        uses: actions/deploy-pages@v1
        with:
          name: github-pages

      - name: Deploy(This action is used to deploy Actions artifacts to GitHub Pages.)
        # if: success()
        id: deployment
        uses: actions/deploy-pages@v1
