name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build:prod

      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: docs
          target-folder: docs #  To push the contents of the deployment
          commit-message: "Contents Of Deployement is done  ${{github.event.head_commit.message}}
