name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build:prod

      #- name: Deploy(This action is used to deploy Actions artifacts to GitHub Pages.)
      # if: success()
      # uses: actions/deploy-pages@v1.2.0
      #  id: deployment

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Deploy static files (Github page - into docs folder)
        uses: peaceiris/actions-gh-pages@v3
        #  if: ${{ github.ref == 'refs/heads/main' }} # Only main branch
        with:
          github_token: ${{secrets.GITHUB_TOKEN}} # set automatically
          keep_files: false # Keeping existing files
          # destination_dir: ./docs # The Folder(from publish_dir ) Where gh-page point his html files
          publish_dir: ./docs # Sources folder to get all html files
          commit_message: ----> ${{github.event.head_commit.message}} <---- # Set custom commit message
          force_orphan: true # allows you to make your publish branch with only the latest commit
          publish_branch: main # Default=gh-pages. Set Another GitHub Pages Branch, but we want under foder docs!!
